#!/bin/bash

mkdir output
cd src
echo "Making lpgenerator"
make clean
make
mv lpgenerator ../
cd ..
echo "Unzipping larger files"
unzip alpha.words.zip
unzip beta.words.zip
unzip other.words.zip
cd trees
unzip alpha.tree.zip
unzip coil.tree.zip
echo "Building matcher"
cd ..
for i in 1 2; do
    cat segment$i >> matcher.zip
    #rm segment$i
done
unzip matcher.zip

