#!/bin/bash

lenwords=23
numthreads=1
k=5
firstitr=1
tag=output
seq=$1
python split.py $seq
iseq=$seq
seq=${seq}.seq
lpgenerator PredictProteinKnnCoil alpha.words beta.words other.words ${seq} $lenwords ${tag}/${seq}.knn $k $firstitr 
python getSecondaryStructure.py ${tag}/${seq}.knn ${tag}/${seq}.knnss 
python overlappingwords.py ${tag}/${seq}.knnss ${tag}/${seq}.probs $tag $k 
python dynamicprogramming.py $iseq ${tag}/${seq}.probs ${tag}/${iseq}.ss
#python convertprobabilities.py ${tag}/${seq}.probs $iseq ${tag}/${iseq}.ss
