#!/bin/bash

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -i|--input)
            seq="$2"
            shift
            shift
            ;;
        -o|--output)
            OUTPUT="$2"
            shift
            shift
            ;;
        -n|--numthreads)
            numthreads="$2"
            shift
            shift
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
    esac
done
set -- "${POSITIONAL[@]}"
echo "done parsing args"
lenwords=23
#numthreads=1
lownumthreads=$(( $numthreads - 1 ))
k=5
firstitr=1
tag=output
if [ -z ${seq+x} ]; then
    seq=$1
fi
iseq=$seq
if [ -z ${OUTPUT+x} ]; then
    OUTPUT=${tag}/${iseq}.ss
fi
python split.py $seq
seq=${seq}.seq
#echo "finding identities"
#python getSecondaryStructure.py $seq ${tag}/${seq}.idents $seq $k
python splitfile.py $seq $numthreads
echo "started knn"
for i in `seq 0 $lownumthreads`; do
    ./lpgenerator PredictProteinKnnCoil alpha.words beta.words other.words ${seq}_${i} $lenwords ${tag}/${seq}.knn_${i} $k $firstitr &
done
wait
echo "end knn"
for i in `seq 0 $lownumthreads`; do
    cat ${tag}/${seq}.knn_${i} >> ${tag}/${seq}.knn
done
python getSecondaryStructure.py ${tag}/${seq}.knn ${tag}/${seq}.knnss 8 1
echo "catting together knnss"
echo "end ss"
#python identstitch.py ${tag}/${seq}.idents ${tag}/${seq}.knnss ${tag}/${seq}.knnss $k
python overlappingwords.py ${tag}/${seq}.knn ${tag}/${seq}.probs $tag $k 
python eightoverlappingwords.py ${tag}/${seq}.knnss ${tag}/${seq}.probs8 $tag $k 
echo "done overlapping"
python dynamicprogramming.py ${tag}/${seq}.probs $OUTPUT 3
python dynamicprogramming.py ${tag}/${seq}.probs8 $OUTPUT 8
echo "writing output"
rm $seq* ${tag}/${seq}.*
#python convertprobabilities.py ${tag}/${seq}.probs $iseq ${tag}/${iseq}.ss
